### ISSUE TITLE
[0.61.0] ReactWebViewManager error

### ISSUE THREAD

**Issue by vivianlamCP** [iou90/react-native-autoheight-webview#164]
react-native-autoheight-webview/android/src/main/java/com/dscj/autoheightwebview/AutoHeightWebViewManager.java:8: error: package com.reactnativecommunity.webview does not exist

import com.reactnativecommunity.webview.RNCWebViewManager;
                                                                         ^

any solution? 

react-native version: 0.61.0

**Comment by iou90** [comment]
What's the version of rnaw? This is a pure js lib now.

**Comment by vivianlamCP** [comment]
I'am using 
+ react-native-autoheight-webview@0.6.1
+ react-native-webview@9.3.0

Cannot solve why get this ReactWebViewManager error after upgrading to 0.61.0 from 0.59.8

/src/main/java/com/dscj/autoheightwebview/AutoHeightWebViewManager.java:8: error: package com.facebook.react.views.webview does not exist
import com.facebook.react.views.webview.ReactWebViewManager;
                                                                       ^

**Comment by iou90** [comment]
Please update your react-native-autoheight-webview to the last version. (https://github.com/iou90/react-native-autoheight-webview/blob/master/README.md)

**Comment by vivianlamCP** [comment]
thanks
