### ISSUE TITLE
add functionality to open hyperlink on default browser(Android)

### ISSUE THREAD

**Issue by samridhgupta** [iou90/react-native-autoheight-webview#19]
So I m using this library's webview to populate my HTML content in my app,
Some of my HTML content contains hyperlinks (href).

**Action:** Taping on hyperlinks in HTML content viewed in this lib's webview.
**Current Outcome:** Hyperlinks load the page in the same webview.
**Expected Outcome:** Hyperlink should open up on an external browser in the device.

Please help me with this scenario for Android devices.
Thanks in advance.

**Comment by iou90** [comment]
I haven't try it before but I wonder what the action of rn WebView is for this scenario.

**Comment by el-lsan** [comment]
@iou90 any chance of considering https://github.com/alinz/react-native-webview-bridge ?

So we can solve this issue by triggering something like following on anchor's `onclick` event:
```
WebViewBridge.send(selector.target.getAttribute("href"));
```
```
<AutoHeightWebView
      ...
      ref="WebViewBridge"
      onBridgeMessage={this.onBridgeMessage.bind(this)}
      ...
/>

onBridgeMessage(message) {
  Linking.canOpenURL(message).then(supported => {
    if (supported) {
      Linking.openURL(message);
    }
  })
}
```

**Comment by nickrobinson352** [comment]
I got it working by intercepting the URL click on onStartLoading()

https://github.com/nickrobinson352/react-native-autoheight-webview/commit/1894efb4b90561759e2e304d46c00ce550e36f89

**Comment by markrickert** [comment]
@nickrobinson352 are you planning to make a PR to this library with your change?

**Comment by iou90** [comment]
https://medium.com/@elhardoum/opening-external-links-in-browser-in-react-native-webview-18fe6a66312a
Anyone try this solution?

**Comment by GoMino** [comment]
@iou90 I confirmed, this solution works with version 0.10.2

**Comment by iou90** [comment]
@GoMino Great! It will help everyone a lot if you can do a PR with this solution to the demo of this repo =w=

**Comment by GoMino** [comment]
@iou90 here you go!

**Comment by ldco2016** [comment]
@el-lsan @iou90 , what exactly is the working solution? I followed this: https://github.com/alinz/react-native-webview-bridge#ios and got this error when I ran the build in Xcode:

```
Undefined symbols for architecture arm64:
  "_RCTJSNavigationScheme", referenced from:
      -[RCTWebViewBridgeManager constantsToExport] in libReact-Native-Webview-Bridge.a(RCTWebViewBridgeManager.o)
      -[RCTWebViewBridge webView:shouldStartLoadWithRequest:navigationType:] in libReact-Native-Webview-Bridge.a(RCTWebViewBridge.o)
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by vish2595** [comment]
@ldco2016 Any solutions you get?
